version: 0.2

phases:
  install:
    commands:
     - Invoke-WebRequest -UseBasicParsing https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi -OutFile AWSCLI64PY3.msi; `
      Start-Process "msiexec.exe"  -ArgumentList '/i', 'AWSCLI64PY3.msi', '/qn', '/norestart' -Wait -NoNewWindow; `
      Remove-Item -Force AWSCLI64PY3.msi; `
  pre_build:
    commands:
        - aws --version
artifacts:
  files:
    - '**/*'
